// generated by Claude 2026/03/24

import ts from 'typescript'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

/////////////////////////////////////////////////

const __dirname = path.dirname(fileURLToPath(import.meta.url))

export const tsconfigⵧlegacy__compilerOptions‿resolved =
	get_tsconfig__compilerOptions‿resolved(path.join(__dirname, '../../~~tosort/2026/v5-non-pkg/tsconfig.json'))


export const tsconfigⵧdefault__compilerOptions‿resolved
	= get_tsconfig__compilerOptions‿resolved()

/////////////////////////////////////////////////

export function Xget_tsconfig__compilerOptions‿resolved(tsconfigPath?: string): ts.CompilerOptions {
	let fileNames: string[] = [];
	let options: ts.CompilerOptions = ts.getDefaultCompilerOptions()

	if (tsconfigPath) {
		const absolutePath = path.resolve(tsconfigPath);

		const configFile = ts.readConfigFile(absolutePath, ts.sys.readFile);
		if (configFile.error) throw new Error(ts.formatDiagnostic(configFile.error, ts.createCompilerHost({})));

		const parsedConfig = ts.parseJsonConfigFileContent(
			configFile.config,
			ts.sys,
			path.dirname(absolutePath)
		);

		fileNames = parsedConfig.fileNames;
		options = parsedConfig.options;
	}

	const resolved = ts.createProgram({
		rootNames: fileNames.length ? fileNames : ['noop.ts'],
		options,
	}).getCompilerOptions();

	return Object.fromEntries(
		Object.entries(resolved).sort(([a], [b]) => a.localeCompare(b))
	) as ts.CompilerOptions;
}

export function get_tsconfig__compilerOptions‿resolved(tsconfigPath?: string) {
	if (!tsconfigPath) return ts.getDefaultCompilerOptions();

	const absolutePath = path.resolve(tsconfigPath);

	// Read and parse the raw tsconfig file (handles `extends`, comments, etc.)
	const configFile = ts.readConfigFile(absolutePath, ts.sys.readFile);

	if (configFile.error) {
		throw new Error(ts.formatDiagnostic(configFile.error, ts.createCompilerHost({})));
	}

	// Resolve the full config — merges extends, applies defaults, resolves paths
	const parsedConfig = ts.parseJsonConfigFileContent(
		configFile.config,
		ts.sys,
		path.dirname(absolutePath)
	);

	if (parsedConfig.errors.length > 0) {
		if (parsedConfig.errors.length === 1 && parsedConfig.errors[0]?.code === 18003) {
			// "no input" = expected, this is a config to be extended
		}
		else {
			throw new Error(parsedConfig.errors.map(e => ts.formatDiagnostic(e, ts.createCompilerHost({}))).join('\n'));
		}
	}
	//parsedConfig.options   // Fully resolved CompilerOptions object
	//fileNames: parsedConfig.fileNames,        // All included files
	//projectReferences: parsedConfig.projectReferences,
	//raw: parsedConfig.raw,                    // The raw merged JSON (before TS normalization)

	const resolved = {
		...ts.getDefaultCompilerOptions(),
		...parsedConfig.options,
	};

	return Object.fromEntries(
		Object.entries(resolved).sort(([a], [b]) => a.localeCompare(b))
	) as ts.CompilerOptions;
}

/////////////////////////////////////////////////

import * as jsondiffpatch from 'jsondiffpatch'
import type { DiffPatcher } from 'jsondiffpatch'

const _raw_comparator = jsondiffpatch.create({
	cloneDiffValues: true, /* default false. if true, values in the obtained delta will be cloned
      (using jsondiffpatch.clone by default), to ensure delta keeps no references to left or right objects.
      This becomes useful if you're diffing and patching the same objects multiple times without serializing deltas.
      instead of true, a function can be specified here to provide a custom clone(value)
      */
})
export const get_raw_diff: DiffPatcher['diff'] = _raw_comparator.diff.bind(_raw_comparator)
