// http://thebedrockblog.blogspot.com/2017/12/legends-of-ogre-gate-chapter-56-sun.html
// https://jeremybai.com/

const BEGINNING = [
	'After the wedding',
	'At the beginning state',
	'If a horse does not resemble a horse',
	'If a man acts without altruism',
	'If a man is without decorum',
	'If a man mistakes the sword for the way',
	'If a man offends The Enlightened Goddess',
	'If a poem stirs your heart and mind',
	'If a virtuous man is lazy',
	'If a word is wrong',
	'If an act is performed without integrity',
	'If an act is performed without propriety+',
	'If an Emperor offends the Enlightened Goddess',
	'If I walk with an enemy+',
	'If I walk with two friends',
	'If one does not seek altruistic company+',
	'If one fails to observe the rites',
	'If one observes hierarchy',
	'If the Emperor takes action',
	'If there is a way to riches+',
	'If there is kindness in your heart',
	'If traditions are not followed',
	'If you act for the sake of gaining wealth and fame',
	'If you are dying',
	'If you are given authority',
	'If you are guided by lust',
	'If you are inconsistent+',
	'If you are the wisest present',
	'If you are upright',
	'If you aspire to Wan Mei',
	'If you break a promise',
	'If you cannot answer a question',
	'If you come by money honestly',
	'If you dislike something',
	'If you elevate the orthodox above the unorthodox',
	'If you fail to see the mountain',
	'If you hear the sounds of the perfect realm',
	'If you honor the rites but ignore the virtues',
	'If you make  a promise',
	'If you make a mistake and others see',
	'If you plan to plant rice+',
	'If you see a mountain',
	'If you see a skyladder',
	'If you see a Zhen Bird',
	'If you see the sun and moon in the sky',
	'If you speak the wrong words',
	'If you understand the perfect realm',
	'If you walk beside a friend',
	'If you want to know how the people are governed',
	'If you wear the sackcloth',
	'If you wish to compose a masterpiece',
	'In the perfect realm',
	'Only when you’ve conquered yourself',
	'When a man breaks the law',
	'When a man has no moustache',
	'When a man is adored by all',
	'When a man is hated by all',
	'When a man kills your father+',
	'When a man lies',
	'When a man mistreats another',
	'When a person must be lectured',
	'When a ruler governs with altruism and rite',
	'When a teacher greets you',
	'When court officials act selfishly',
	'When men of virtue speak',
	'When one speaks',
	'When the emperor asks',
	'When the heart is restful',
	'When the magistrate arrives',
	'When the northerners invade',
	'When the reed bends+',
	'When the ruler is punished',
	'When things are most tumultuous',
	'When you act with no dignity',
	'When you act without loyalty',
	'When you act without respect',
	'When you are busy',
	'When you are conquered by yourself',
	'When you are divorced+',
	'When you are flawed',
	'When you climb the five peaks',
	'When you demand much from yourself',
	'When you expect little from others',
	'When you fail in your task',
	'When you go to war+',
	'When you have no money',
	'When you know something',
	'When you respect your elders',
	'When you see a man of bad character',
	'When you see a worthy teacher',
	'When you see Mount Dao',
	'When you see the perfect realm',
	'When you speak without modesty',
	'When you spend 100 golden taels',
	'When you strike with a sword',
	'Wherever you may go',
	'While others fish',
	'With ten taels of gold',
	'Without a master',
	'Without knowledge',
]

const END = [
	'is this not man?',
	'only then can you be a true scholar',
	'you never truly work',
	'adapt and live according to Wan Mei',
	'an axe cannot be wielded',
	'analyze carefully and cautiously+',
	'animal are the same as men',
	'be rigid and refuse to compromise',
	'bring forth the manacles and demonstrate the law',
	'conceal your resentment',
	'consider how this all came to be',
	'do not shatter the peace',
	'do not waste your breath',
	'draw your sword',
	'educate your children+',
	'examine your eyes and ears first',
	'focus with all your might',
	'forget what you know, remember what you do not know',
	'give a sword to the one who cannot dance',
	'how can you understand ritual and virtue?',
	'investigate the matter thoroughly',
	'it is because of good fortune+',
	'it is impossible to know less',
	'it is needless to speak of such things',
	'it is not the time for change',
	'it is unfilial not to kill',
	'kill the soldiers but spare the innocent',
	'lead the people with proper rite and righteousness+',
	'leave without waiting for food or horses',
	'let the people despise you',
	'many will rise against you',
	'men and beasts are the same',
	'one finds the perfect state',
	'only then should you kill',
	'pay the proper respects',
	'plant hemp',
	'prepare a meal and take your time',
	'proper performance of the rite is crucial',
	'remember the proper way to greet a guest and say good bye',
	'strike at the foundation',
	'the Emperor is no longer deserving of awe',
	'the Emperor is worthy and should be deserving of awe',
	'the answer is found in song and dance',
	'the law cannot be changed',
	'the law has been broken',
	'the mandate of heaven is lost+',
	'the mandate of heaven is secure',
	'the mind awakens',
	'the mourning can end',
	'the oak will break',
	'the people will be governed',
	'the perfect realm cannot be seen',
	'the perfect realm is before you',
	'the world falls apart',
	'the world of man is without order',
	'the world will be more harmonious',
	'then dignity is without pride',
	'then the frost on the pines and the withered leaves become clear',
	'then the ignorant should listen',
	'then there is no place to make an offering+',
	'then there is no shame',
	'then words cannot take form',
	'then you should retire and dig yourself a grave',
	'then you will never make mistakes',
	'there is no law',
	'there is no wickedness',
	'there is nothing more lower than this',
	'there will be beauty in your heart',
	'this is a burden+',
	'this is a great soldier',
	'this is called Wan Mei',
	'this is called being Filial',
	'this is called evil',
	'this is ignorance',
	'this is not the time to govern',
	'turn inward and seek change',
	'walk slow and measure your breath',
	'what is there to fear?',
	'what will the gods do?',
	'where can one obtain true insight?',
	'words may stay the same but their meaning changes',
	'write down all events and record them accurately+',
	'you already know what must be done',
	'you are in the perfect realm',
	'you are surrounded by evil',
	'you are surrounded by fools',
	'you are surrounded by sages',
	'you bring honor to your name+',
	'you have found a worthy teacher',
	'you must kill and strike without mercy',
	'you must never change course',
	'you must sharpen the necessary tools',
	'you must still find time to read and study',
	'you never know how sharp the blade is',
	'you shame and disgrace your family',
	'you should obtain all the gold you can+',
	'you should resist with all your might',
	'you will live without resentment',
	'your friends will celebrate and mourn',
	'your heart will be at peace',
]

const BONUS = [
	'but not all men can see the perfect realm',
	'but the achievement is without meaning',
	'but the perfect realm cannot truly be attained',
	'but the wise never do such things',
	'but then you must become a scholar',
	'but this cannot be done without losing honor',
	'but you will be filled with shame',
	'but you will never truly see again',
	'or there will be no peace',
	'or you will never understand Wan Mei',
]

function getRandomInt(min, max) {
	min = Math.ceil(min);
	max = Math.floor(max);
	return Math.floor(Math.random() * (max - min) + min); // The maximum is exclusive and the minimum is inclusive
}

function getRandomIntInclusive(min, max) {
	min = Math.ceil(min);
	max = Math.floor(max);
	return Math.floor(Math.random() * (max - min + 1) + min); // The maximum is inclusive and the minimum is inclusive
}

function gen() {
	let special = 0
	let part1 = BEGINNING[getRandomInt(0, BEGINNING.length)]
	if (part1.endsWith('+')) {
		special++
		part1 = part1.slice(0, -1)
	}
	let part2 = END[getRandomInt(0, END.length)]
	if (part2.endsWith('+')) {
		special++
		part2 = part2.slice(0, -1)
	}
	const part3 = special === 2 ? BONUS[getRandomInt(0, BONUS.length)] : ''
	let result = [part1, part2, part3]
		.filter(p => !!p)
		.join(', ')
	if (!result.endsWith('?'))
		result += '.'

	return result
}

console.log(gen())
console.log(gen())
console.log(gen())
console.log(gen())
