// THIS FILE IS AUTO GENERATED

interface FirstNameEntry {
	str: string
	gender: 'M' | 'F' | 'N'
	tags: string[]
	associations: string[]
}

const FIRST_NAME_ENTRIES: FirstNameEntry[] = [
{
	str: 'Guoqing',
	gender: 'M',
	tags: [ '#common' ],
	associations: [ 'national day holiday in china' ],
},
{
	str: 'Guo',
	gender: 'M',
	tags: [ '#common' ],
	associations: [ 'country', 'nation' ],
},
{
	str: 'Qing',
	gender: 'N',
	tags: [ '#artisan', '#bandit', '#common', '#dark', '#doctor', '#dramatic', '#dramatic', '#dramatic', '#dramatic', '#dramatic', '#dramatic', '#farmer', '#gender-neutral', '#government_official', '#loyalist', '#merchant', '#scholar', '#uncommon', '#uncommon', '#uncommon' ],
	associations: [ 'affection', 'azure', 'blue', 'bright', 'celebrate', 'celebration', 'clear', 'dignitary', 'emotion', 'feeling', 'fine', 'green', 'high-ranking official', 'minister', 'official', 'passion', 'sentiment', 'strong', 'violent' ],
},
{
	str: 'Haitao',
	gender: 'M',
	tags: [ '#common' ],
	associations: [ 'ocean waves' ],
},
{
	str: 'Hai',
	gender: 'N',
	tags: [ '#common', '#common', '#farmer', '#fisher', '#fisher' ],
	associations: [ 'ocean', 'sea' ],
},
{
	str: 'Tao',
	gender: 'M',
	tags: [ '#common', '#fisher' ],
	associations: [ 'big wave' ],
},
{
	str: 'Aimin',
	gender: 'M',
	tags: [ '#common' ],
	associations: [ 'army', 'care for the common people (usually said of a ruler', 'etc.)', 'official' ],
},
{
	str: 'Ai',
	gender: 'N',
	tags: [ '#common', '#shop_owner', '#thief' ],
	associations: [ 'chinese mugwort', 'love' ],
},
{
	str: 'Min',
	gender: 'M',
	tags: [ '#common' ],
	associations: [ 'citizens', 'clan', 'people' ],
},
{
	str: 'Xiao',
	gender: 'N',
	tags: [ '#common', '#common', '#constable', '#dedicated_martial_practitioner', '#dramatic', '#entertainer', '#gender-neutral', '#government_official', '#playboy/young_master', '#righteous', '#soldier' ],
	associations: [ 'bleak', 'cloud', 'desolate', 'dreary', 'firmament', 'heaven', 'hiss', 'laugh', 'little', 'miserable', 'sky', 'small', 'smile', 'whistle' ],
},
{
	str: 'Fan',
	gender: 'N',
	tags: [ '#common', '#gender-neutral' ],
	associations: [ 'mortal', 'mundane', 'normal', 'ordinary' ],
},
{
	str: 'Yawen',
	gender: 'N',
	tags: [ '#common' ],
	associations: [ 'refined and elegant' ],
},
{
	str: 'Ya',
	gender: 'N',
	tags: [ '#beggar', '#common', '#scholar' ],
	associations: [ 'cliff', 'elegant', 'girl', 'precipice' ],
},
{
	str: 'Wen',
	gender: 'N',
	tags: [ '#artisan', '#common', '#dedicated_martial_practitioner', '#detective', '#dramatic', '#dramatic', '#scholar', '#uncommon' ],
	associations: [ 'ask', 'culture', 'inquire', 'language', 'writing' ],
},
{
	str: 'Lei',
	gender: 'N',
	tags: [ '#common' ],
	associations: [ 'heap of stones', 'open and honest' ],
},
{
	str: 'Hua',
	gender: 'N',
	tags: [ '#common', '#constable', '#detective', '#doctor', '#farmer' ],
	associations: [ 'beautiful', 'blossom', 'china', 'flower', 'flowery', 'glorious', 'splendid' ],
},
{
	str: 'Jing',
	gender: 'N',
	tags: [ '#assassin', '#common', '#constable', '#government_official', '#government_official', '#scholar' ],
	associations: [ 'admire', 'brambles', 'bright', 'chaste tree (a type of tree)', 'circumstance', 'glass', 'lens', 'mirror', 'offer', 'respect', 'revere', 'salute', 'scenery', 'thorns', 'venerate' ],
},
{
	str: 'Meili',
	gender: 'F',
	tags: [ '#common' ],
	associations: [ 'beautiful' ],
},
{
	str: 'Mei',
	gender: 'F',
	tags: [ '#bandit', '#common', '#dramatic', '#farmer' ],
	associations: [ 'beautiful', 'bewitching', 'charming', 'good', 'pretty', 'younger sister' ],
},
{
	str: 'Li',
	gender: 'N',
	tags: [ '#assassin', '#bandit', '#common', '#dark', '#dedicated_martial_practitioner', '#dramatic' ],
	associations: [ 'beautiful', 'colored glaze', 'dew', 'establish', 'glass', 'gorgeous', 'gravel', 'leave', 'part from', 'ravishing', 'set up', 'small stone', 'stand', 'syrup' ],
},
{
	str: 'Xiu',
	gender: 'F',
	tags: [ '#beggar', '#common', '#doctor' ],
	associations: [ 'beautiful', 'elegant', 'excellent', 'graceful', 'handsome', 'refined' ],
},
{
	str: 'Ying',
	gender: 'N',
	tags: [ '#assassin', '#common', '#dramatic', '#righteous', '#soldier', '#soldier' ],
	associations: [ 'clever', 'excellent', 'gifted', 'hero', 'luster of gems', 'outstanding', 'shadow' ],
},
{
	str: 'Rong',
	gender: 'N',
	tags: [ '#common', '#soldier' ],
	associations: [ 'glory', 'honor', 'prosperous', 'thriving', 'weapon' ],
},
{
	str: 'Changqing',
	gender: 'M',
	tags: [ '#dramatic', '#uncommon' ],
	associations: [ 'a rare word for butterfly', 'an archaic word for butterfly' ],
},
{
	str: 'Chang',
	gender: 'N',
	tags: [ '#dramatic', '#government_official', '#uncommon' ],
	associations: [ 'fluent', 'free', 'joyful', 'long', 'smooth' ],
},
{
	str: 'Yuan',
	gender: 'N',
	tags: [ '#dedicated_martial_practitioner', '#dramatic', '#gender-neutral', '#loyalist', '#thief', '#uncommon', '#uncommon' ],
	associations: [ '', 'city', 'first', 'long robe', 'origin', 'original', 'root', 'source', 'wall' ],
},
{
	str: 'Chen',
	gender: 'N',
	tags: [ '#artisan', '#dramatic', '#dramatic', '#gender-neutral', '#gender-neutral', '#uncommon' ],
	associations: [ 'celestial bodies', 'celestial bodies. fifth earthly branch', 'dawn', 'daybreak', 'dirt', 'dust', 'earth', 'fifth earthly branch', 'imperial palace', 'mansion', 'morning', 'throne' ],
},
{
	str: 'Yi',
	gender: 'N',
	tags: [ '#artisan', '#doctor', '#dramatic', '#entertainer', '#entertainer', '#entertainer', '#gender-neutral', '#gender-neutral', '#righteous', '#thief', '#uncommon' ],
	associations: [ 'art', 'escape', 'firm', 'first', 'happy', 'harmony', 'joyful', 'leisurely', 'memory', 'one', 'outstanding', 'remember', 'resolute', 'restrain', 'skill', 'staunch', 'virtuous' ],
},
{
	str: 'Tai',
	gender: 'M',
	tags: [ '#uncommon' ],
	associations: [ 'grand', 'peaceful', 'safe' ],
},
{
	str: 'Yan',
	gender: 'N',
	tags: [ '#dark', '#doctor', '#dramatic', '#dramatic', '#dramatic', '#entertainer', '#farmer', '#fisher', '#government_official', '#servant', '#thief', '#uncommon', '#uncommon' ],
	associations: [ 'accomplished', 'amorous', 'amplify', 'beautiful', 'captivating', 'colorful', 'develop', 'elegant', 'fire', 'flame', 'gaudy', 'mist', 'smoke', 'speech', 'swallow (bird)', 'to spread out', 'vapor', 'word', 'words' ],
},
{
	str: 'Ze',
	gender: 'N',
	tags: [ '#uncommon' ],
	associations: [ 'damp', 'moist', 'pond', 'pool' ],
},
{
	str: 'Nan',
	gender: 'N',
	tags: [ '#dramatic', '#gender-neutral', '#thief', '#uncommon' ],
	associations: [ 'cedar', 'redwood', 'south' ],
},
{
	str: 'Sheng',
	gender: 'N',
	tags: [ '#artisan', '#beggar', '#uncommon' ],
	associations: [ 'be left', 'birth', 'grow', 'have as a remainder', 'life', 'remain' ],
},
{
	str: 'Xi',
	gender: 'N',
	tags: [ '#dramatic', '#dramatic', '#dramatic', '#farmer', '#scholar', '#servant', '#shop_owner', '#uncommon' ],
	associations: [ 'bathe', 'be fond of', 'delight', 'enjoy', 'happiness', 'happy', 'hope', 'light of day', 'like', 'love', 'no meaning. this character is an exclamatory particle.', 'prosperous', 'splendid', 'to like', 'wash' ],
},
{
	str: 'Zi',
	gender: 'N',
	tags: [ '#beggar', '#dramatic', '#dramatic', '#gender-neutral', '#playboy/young_master', '#scholar', '#scholar', '#servant', '#soldier', '#uncommon' ],
	associations: [ 'catalpa (a genus of flowering plants)', 'child', 'first earthly branch', 'mauve', 'purple', 'son', 'violet' ],
},
{
	str: 'Qi',
	gender: 'N',
	tags: [ '#constable', '#gender-neutral', '#shop_owner', '#uncommon' ],
	associations: [ 'felicity', 'intiate', 'lucky', 'open', 'seven', 'seventh', 'start' ],
},
{
	str: 'Yu',
	gender: 'N',
	tags: [ '#detective', '#doctor', '#dramatic', '#dramatic', '#farmer', '#fisher', '#government_official', '#government_official', '#loyalist', '#merchant', '#merchant', '#playboy/young_master', '#playboy/young_master', '#playboy/young_master', '#servant', '#servant', '#shop_owner', '#uncommon' ],
	associations: [ 'abundant', 'cluster of gems', 'excellence', 'feather', 'fish', 'jade', 'language', 'opulent', 'plentiful', 'rain', 'speech', 'to go', 'to take' ],
},
{
	str: 'Ke',
	gender: 'N',
	tags: [ '#assassin', '#uncommon' ],
	associations: [ '', 'approve', 'can', 'carraige', 'may' ],
},
{
	str: 'Tian',
	gender: 'N',
	tags: [ '#bandit', '#dark', '#dramatic', '#dramatic', '#dramatic', '#gender-neutral', '#loyalist', '#loyalist', '#loyalist', '#playboy/young_master', '#righteous', '#righteous', '#servant', '#servant' ],
	associations: [ 'calm', 'farm', 'field', 'heaven', 'peaceful', 'qiet', 'sky', 'tranquil' ],
},
{
	str: 'Ba',
	gender: 'M',
	tags: [ '#bandit', '#dark' ],
	associations: [ 'bully', 'dominate', 'hegemon', 'tyrant' ],
},
{
	str: 'Ao',
	gender: 'M',
	tags: [ '#dark' ],
	associations: [ 'arrogant', 'proud', 'unyielding' ],
},
{
	str: 'Xue',
	gender: 'N',
	tags: [ '#assassin', '#assassin', '#dark', '#dramatic' ],
	associations: [ 'blood', 'snow', 'snowfall' ],
},
{
	str: 'Wan',
	gender: 'N',
	tags: [ '#dark', '#dramatic', '#dramatic', '#fisher', '#merchant', '#merchant', '#scholar' ],
	associations: [ 'bind up', 'countless', 'graceful', 'myriad', 'similar', 'string together', 'tactful', 'ten thousand', 'winding' ],
},
{
	str: 'Chou',
	gender: 'N',
	tags: [ '#dark', '#dark' ],
	associations: [ 'anxious', 'enemy', 'foe', 'grudge', 'hate', 'loathe', 'worry about' ],
},
{
	str: 'Luo',
	gender: 'N',
	tags: [ '#assassin', '#dark' ],
	associations: [ 'luo river', 'net', 'sieve', 'to collect' ],
},
{
	str: 'Shang',
	gender: 'N',
	tags: [ '#dark', '#doctor', '#righteous', '#thief' ],
	associations: [ 'above', 'die in war', 'die young', 'go up', 'lower garment', 'skirts', 'still', 'upon', 'upper', 'yet' ],
},
{
	str: 'Leng',
	gender: 'N',
	tags: [ '#beggar', '#dark' ],
	associations: [ 'cold', 'corner', 'edge' ],
},
{
	str: 'Sha',
	gender: 'N',
	tags: [ '#assassin', '#assassin', '#beggar', '#dark' ],
	associations: [ 'brake', 'foolish', 'powder', 'sand', 'stop. (this character is pronounced the same and resembles the character for “kill” 杀)', 'stop. (when used alone', 'stupid', 'this character is pronounced the same and resembles the character for “kill” 杀)' ],
},
{
	str: 'Wuqing',
	gender: 'N',
	tags: [ '#dark' ],
	associations: [ 'merciless', 'pitiless', 'ruthless' ],
},
{
	str: 'Wu',
	gender: 'N',
	tags: [ '#assassin', '#dark', '#loyalist', '#soldier' ],
	associations: [ 'fierce', 'lacking', 'martial', 'no', 'valiant', 'without' ],
},
{
	str: 'Mochou',
	gender: 'F',
	tags: [ '#dark' ],
	associations: [ 'li mouchou', 'this is the given name of a famous wuxia villainess' ],
},
{
	str: 'Mo',
	gender: 'N',
	tags: [ '#dark', '#dark', '#dramatic', '#dramatic' ],
	associations: [ 'black', 'do not', 'foam', 'footway', 'froth', 'ink', 'path', 'saliva', 'tattoo', 'there is none who' ],
},
{
	str: 'Yue',
	gender: 'N',
	tags: [ '#assassin', '#constable', '#dark', '#dramatic', '#government_official', '#playboy/young_master', '#scholar' ],
	associations: [ 'accede', 'amputate the feet as punishment', 'assent', 'delighted', 'happy', 'moon', 'music', 'pleased' ],
},
{
	str: 'Ling',
	gender: 'N',
	tags: [ '#constable', '#dark', '#detective', '#gender-neutral' ],
	associations: [ 'alert', 'approach', 'damask', 'intimidate', 'quick', 'rise high', 'spirit', 'the sound of flowing water', 'thin silk' ],
},
{
	str: 'Jie',
	gender: 'N',
	tags: [ '#constable', '#dark', '#detective', '#righteous', '#shop_owner' ],
	associations: [ 'heroic', 'older sister', 'oustanding', 'outstanding', 'prominent' ],
},
{
	str: 'Zhan',
	gender: 'M',
	tags: [ '#constable', '#dramatic', '#righteous' ],
	associations: [ 'exhibit', 'open', 'open up', 'spread out' ],
},
{
	str: 'Peng',
	gender: 'M',
	tags: [ '#righteous' ],
	associations: [ 'a mythological bird sometimes translated as “roc”', 'the peng' ],
},
{
	str: 'Zheng',
	gender: 'M',
	tags: [ '#dramatic', '#government_official', '#righteous' ],
	associations: [ 'positive', 'proper', 'right', 'upright' ],
},
{
	str: 'Feng',
	gender: 'N',
	tags: [ '#dedicated_martial_practitioner', '#dramatic', '#dramatic', '#dramatic', '#entertainer', '#farmer', '#government_official', '#loyalist', '#playboy/young_master', '#righteous', '#righteous', '#scholar' ],
	associations: [ 'abundant', 'lavish', 'luxuriant', 'maple', 'phoenix', 'plentiful', 'tree name', 'vast', 'wind', 'wing' ],
},
{
	str: 'Yun',
	gender: 'N',
	tags: [ '#artisan', '#constable', '#dedicated_martial_practitioner', '#entertainer', '#righteous', '#shop_owner' ],
	associations: [ 'cloud' ],
},
{
	str: 'Wei',
	gender: 'N',
	tags: [ '#detective', '#dramatic', '#loyalist', '#righteous', '#soldier' ],
	associations: [ 'defend', 'did not', 'dynasty/kingdom name', 'eighth earthly branch', 'guard', 'have not', 'micro', 'minute', 'plant name', 'protect', 'tiny', 'tower' ],
},
{
	str: 'Shan',
	gender: 'N',
	tags: [ '#fisher', '#righteous' ],
	associations: [ 'mountain' ],
},
{
	str: 'Lin',
	gender: 'N',
	tags: [ '#beggar', '#playboy/young_master', '#righteous', '#servant' ],
	associations: [ 'continuous rain', 'forest', 'jungle' ],
},
{
	str: 'Yao',
	gender: 'N',
	tags: [ '#assassin', '#bandit', '#detective', '#righteous' ],
	associations: [ 'a name', 'ask for', 'demand', 'jade', 'jasper', 'junior', 'mother-of-pearl', 'nacre', 'one', 'request', 'tiny', 'want' ],
},
{
	str: 'Jia',
	gender: 'N',
	tags: [ '#entertainer', '#gender-neutral', '#righteous', '#soldier' ],
	associations: [ 'auspicious', 'beautiful', 'commend', 'excellent', 'fine', 'glorious', 'good', 'great', 'praise', 'pretty' ],
},
{
	str: 'Chu',
	gender: 'F',
	tags: [ '#righteous', '#soldier' ],
	associations: [ 'clear', 'distinct', 'neat' ],
},
{
	str: 'Qiao',
	gender: 'N',
	tags: [ '#dramatic', '#righteous', '#soldier' ],
	associations: [ 'high', 'tall' ],
},
{
	str: 'Yang',
	gender: 'M',
	tags: [ '#artisan', '#artisan', '#dramatic' ],
	associations: [ 'flutter', 'hoist', 'hot', 'masculine (from yin and yang)', 'positive', 'raise', 'sun' ],
},
{
	str: 'Qiu',
	gender: 'M',
	tags: [ '#dramatic' ],
	associations: [ 'autumn', 'fall' ],
},
{
	str: 'Guan',
	gender: 'N',
	tags: [ '#bandit', '#detective', '#dramatic', '#merchant' ],
	associations: [ 'coil up', 'crest', 'crown', 'follow', 'hat', 'observe', 'penetrate', 'pierce', 'string together', 'view', 'watch' ],
},
{
	str: 'Jian',
	gender: 'N',
	tags: [ '#dedicated_martial_practitioner', '#dedicated_martial_practitioner', '#dramatic', '#soldier' ],
	associations: [ 'meet', 'see', 'sword' ],
},
{
	str: 'Huan',
	gender: 'N',
	tags: [ '#dramatic', '#playboy/young_master' ],
	associations: [ 'joyous', 'jubilant', 'merry' ],
},
{
	str: 'Zhuang',
	gender: 'N',
	tags: [ '#dramatic' ],
	associations: [ 'makeup', 'to adorn', 'to dress up' ],
},
{
	str: 'Hen',
	gender: 'N',
	tags: [ '#assassin', '#dramatic', '#servant' ],
	associations: [ 'mark', 'scar', 'traces' ],
},
{
	str: 'Yin',
	gender: 'N',
	tags: [ '#assassin', '#doctor', '#dramatic', '#merchant' ],
	associations: [ 'chant', 'concealed', 'hidden', 'moan', 'peaceful', 'recite', 'secret', 'silver', 'solemn' ],
},
{
	str: 'Meng',
	gender: 'F',
	tags: [ '#artisan', '#dramatic', '#dramatic', '#dramatic' ],
	associations: [ 'dream', 'to dream' ],
},
{
	str: 'Zhen',
	gender: 'N',
	tags: [ '#doctor', '#dramatic', '#scholar', '#shop_owner' ],
	associations: [ 'chase', 'gem', 'pillow', 'precious thing', 'rare', 'rest one’s head in sleep', 'treasure' ],
},
{
	str: 'Mingyue',
	gender: 'F',
	tags: [ '#dramatic' ],
	associations: [ 'bright moon' ],
},
{
	str: 'Ming',
	gender: 'N',
	tags: [ '#assassin', '#constable', '#detective', '#dramatic', '#entertainer', '#gender-neutral', '#merchant', '#servant' ],
	associations: [ 'bright', 'brightness', 'brilliant', 'dark', 'deep', 'justice', 'ring', 'sing', 'sound', 'underworld', 'young tea leaves' ],
},
{
	str: 'Mian',
	gender: 'M',
	tags: [ '#dramatic' ],
	associations: [ 'sleep' ],
},
{
	str: 'Niao',
	gender: 'N',
	tags: [ '#dramatic' ],
	associations: [ 'delicate', 'graceful', 'ochre' ],
},
{
	str: 'Mu',
	gender: 'N',
	tags: [ '#artisan', '#dramatic', '#dramatic', '#soldier' ],
	associations: [ 'admire', 'timber', 'tree', 'wood' ],
},
{
	str: 'Qiaomu',
	gender: 'N',
	tags: [ '#dramatic' ],
	associations: [ 'tall tree' ],
},
{
	str: 'Ge',
	gender: 'N',
	tags: [ '#detective', '#dramatic', '#dramatic', '#fisher' ],
	associations: [ 'song' ],
},
{
	str: 'Xing',
	gender: 'N',
	tags: [ '#dramatic', '#playboy/young_master' ],
	associations: [ 'heavenly body', 'star' ],
},
{
	str: 'Han',
	gender: 'M',
	tags: [ '#dramatic' ],
	associations: [ 'ocean', 'vastness' ],
},
{
	str: 'Hao',
	gender: 'M',
	tags: [ '#dramatic', '#dramatic', '#government_official' ],
	associations: [ 'grand', 'great', 'heroic', 'outstanding', 'vast' ],
},
{
	str: 'Zhengnan',
	gender: 'M',
	tags: [ '#dramatic' ],
	associations: [ 'due south' ],
},
{
	str: 'Shao',
	gender: 'N',
	tags: [ '#dramatic', '#shop_owner' ],
	associations: [ 'few', 'less', 'seldom', 'tip of branch' ],
},
{
	str: 'Long',
	gender: 'M',
	tags: [ '#dramatic' ],
	associations: [ 'dragon' ],
},
{
	str: 'Bo',
	gender: 'N',
	tags: [ '#dramatic', '#fisher', '#scholar' ],
	associations: [ 'count', 'obtain', 'plentiful', 'rich', 'rippled', 'senior', 'storm', 'uncle', 'wave', 'win' ],
},
{
	str: 'Qingtian',
	gender: 'M',
	tags: [ '#dramatic' ],
	associations: [ 'blue sky', 'clear sky' ],
},
{
	str: 'Qiankun',
	gender: 'M',
	tags: [ '#dramatic' ],
	associations: [ 'heaven and earth', 'the cosmos', 'the universe', 'yin and yang' ],
},
{
	str: 'Qian',
	gender: 'N',
	tags: [ '#artisan', '#dramatic', '#dramatic', '#merchant', '#thief', '#thief' ],
	associations: [ 'change', 'heaven', 'male', 'many', 'modest', 'money', 'move', 'one of the eight trigrams', 'shift', 'thousand', 'yang-related' ],
},
{
	str: 'Kun',
	gender: 'N',
	tags: [ '#dramatic', '#shop_owner' ],
	associations: [ 'earth', 'female', 'feminine', 'one of the eight trigrams', 'yin-related' ],
},
{
	str: 'Yanyu',
	gender: 'F',
	tags: [ '#dramatic' ],
	associations: [ 'drizzle', 'misty rain' ],
},
{
	str: 'Ting',
	gender: 'F',
	tags: [ '#dramatic' ],
	associations: [ 'graceful' ],
},
{
	str: 'Ruo',
	gender: 'F',
	tags: [ '#dramatic' ],
	associations: [ 'as', 'if', 'like', 'seem' ],
},
{
	str: 'Si',
	gender: 'N',
	tags: [ '#beggar', '#detective', '#doctor', '#dramatic', '#loyalist', '#thief' ],
	associations: [ 'consider', 'four', 'fourth', 'think', 'thought' ],
},
{
	str: 'Yanran',
	gender: 'F',
	tags: [ '#dramatic' ],
	associations: [ 'beautiful', 'engaging', 'gracious', 'sweet' ],
},
{
	str: 'Ran',
	gender: 'F',
	tags: [ '#dramatic' ],
	associations: [ 'correct', 'right' ],
},
{
	str: 'Shu',
	gender: 'N',
	tags: [ '#dramatic', '#government_official' ],
	associations: [ 'book', 'relax', 'smooth away', 'smooth down' ],
},
{
	str: 'Xin',
	gender: 'N',
	tags: [ '#assassin', '#dramatic', '#entertainer', '#loyalist', '#playboy/young_master' ],
	associations: [ 'confidence', 'faith', 'glad', 'happy', 'heart', 'joyful', 'mind', 'trust' ],
},
{
	str: 'Ziwei',
	gender: 'F',
	tags: [ '#dramatic' ],
	associations: [ 'crape myrtle (a tree that usually has purplish flowers)' ],
},
{
	str: 'Ye',
	gender: 'N',
	tags: [ '#assassin', '#dedicated_martial_practitioner', '#farmer', '#gender-neutral', '#shop_owner' ],
	associations: [ 'business', 'gentleman', 'grandfather', 'industry', 'leaf', 'master', 'night', 'profession' ],
},
{
	str: 'Qiming',
	gender: 'N',
	tags: [ '#gender-neutral' ],
	associations: [ 'classical chinese name for planet venus' ],
},
{
	str: 'Nuo',
	gender: 'N',
	tags: [ '#gender-neutral' ],
	associations: [ 'consent', 'promise' ],
},
{
	str: 'Shuo',
	gender: 'N',
	tags: [ '#gender-neutral' ],
	associations: [ 'big', 'large' ],
},
{
	str: 'Qingyang',
	gender: 'M',
	tags: [ '#artisan' ],
	associations: [ 'spring', 'youth' ],
},
{
	str: 'Fei',
	gender: 'N',
	tags: [ '#artisan', '#artisan', '#dedicated_martial_practitioner', '#thief', '#thief', '#thief', '#thief' ],
	associations: [ 'flight', 'fly' ],
},
{
	str: 'Feiyang',
	gender: 'M',
	tags: [ '#artisan' ],
	associations: [ 'fly upward', 'rise' ],
},
{
	str: 'Daqian',
	gender: 'M',
	tags: [ '#artisan' ],
	associations: [ 'chiliocosm', 'the infinite universe' ],
},
{
	str: 'Da',
	gender: 'N',
	tags: [ '#artisan', '#beggar', '#dedicated_martial_practitioner', '#farmer' ],
	associations: [ 'big', 'grand', 'great' ],
},
{
	str: 'Di',
	gender: 'N',
	tags: [ '#artisan' ],
	associations: [ 'direct', 'enlighten', 'favor' ],
},
{
	str: 'Zhuo',
	gender: 'N',
	tags: [ '#artisan', '#servant' ],
	associations: [ 'eminent', 'eminient', 'erect', 'outstanding', 'tall' ],
},
{
	str: 'Chong',
	gender: 'N',
	tags: [ '#artisan', '#bandit' ],
	associations: [ 'charge', 'clash', 'high', 'lofty', 'strong', 'sublime', 'worship' ],
},
{
	str: 'Xia',
	gender: 'N',
	tags: [ '#artisan', '#dedicated_martial_practitioner', '#fisher', '#servant' ],
	associations: [ 'brave', 'chivalrous', 'hero', 'red clouds', 'summer', 'sunrise glow', 'sunset glow' ],
},
{
	str: 'Fu',
	gender: 'N',
	tags: [ '#artisan', '#doctor', '#merchant', '#merchant', '#servant' ],
	associations: [ 'blessing', 'float', 'fortune', 'luck', 'mark', 'seal', 'superficial', 'symbol', 'talisman', 'to recover', 'to resume', 'to return', 'unstable' ],
},
{
	str: 'Zhu',
	gender: 'N',
	tags: [ '#artisan', '#farmer', '#merchant', '#merchant' ],
	associations: [ 'bamboo', 'bead', 'column', 'pearl', 'pillar', 'post' ],
},
{
	str: 'Jing ke',
	gender: 'M',
	tags: [ '#assassin' ],
	associations: [ 'a famous historical assassin' ],
},
{
	str: 'Wuxin',
	gender: 'N',
	tags: [ '#assassin' ],
	associations: [ 'mindless', 'the mind free from illusion', 'without thought' ],
},
{
	str: 'Canyue',
	gender: 'N',
	tags: [ '#assassin' ],
	associations: [ 'waning moon' ],
},
{
	str: 'Can',
	gender: 'N',
	tags: [ '#assassin' ],
	associations: [ 'fragmented', 'incomplete' ],
},
{
	str: 'Ning',
	gender: 'N',
	tags: [ '#assassin', '#soldier' ],
	associations: [ 'concentrate', 'congeal', 'peaceful', 'tranquil' ],
},
{
	str: 'Niang',
	gender: 'F',
	tags: [ '#assassin', '#bandit', '#dedicated_martial_practitioner', '#thief' ],
	associations: [ 'mother', 'woman', 'young lady' ],
},
{
	str: 'Luocha',
	gender: 'F',
	tags: [ '#assassin' ],
	associations: [ 'raksha', 'rakshasa (demons that devour men)' ],
},
{
	str: 'Sang',
	gender: 'N',
	tags: [ '#bandit', '#servant' ],
	associations: [ 'funeral', 'mourning', 'white mulberry' ],
},
{
	str: 'Biao',
	gender: 'M',
	tags: [ '#bandit' ],
	associations: [ 'tiger cub', 'tiger stripes' ],
},
{
	str: 'Hei',
	gender: 'N',
	tags: [ '#bandit', '#beggar' ],
	associations: [ 'black', 'dark' ],
},
{
	str: 'Gou',
	gender: 'M',
	tags: [ '#bandit', '#beggar', '#beggar' ],
	associations: [ 'dog' ],
},
{
	str: 'Zhang',
	gender: 'N',
	tags: [ '#bandit' ],
	associations: [ 'open', 'spread' ],
},
{
	str: 'Du',
	gender: 'N',
	tags: [ '#bandit' ],
	associations: [ 'prevent', 'stop' ],
},
{
	str: 'Shisan',
	gender: 'N',
	tags: [ '#bandit' ],
	associations: [ 'thirteen', 'thirteenth' ],
},
{
	str: 'Shi',
	gender: 'N',
	tags: [ '#bandit', '#beggar', '#doctor', '#entertainer' ],
	associations: [ 'expert', 'hour', 'master', 'period', 'rock', 'season', 'stone', 'teacher', 'ten', 'tenth', 'time' ],
},
{
	str: 'San',
	gender: 'N',
	tags: [ '#bandit', '#dedicated_martial_practitioner', '#merchant', '#servant' ],
	associations: [ 'third', 'three' ],
},
{
	str: 'Er',
	gender: 'N',
	tags: [ '#bandit', '#beggar', '#beggar', '#dedicated_martial_practitioner', '#farmer', '#playboy/young_master', '#thief' ],
	associations: [ 'child', 'or a sound word', 'second', 'son', 'two' ],
},
{
	str: 'Bai',
	gender: 'F',
	tags: [ '#bandit', '#doctor' ],
	associations: [ 'pure', 'white' ],
},
{
	str: 'Lian',
	gender: 'F',
	tags: [ '#bandit' ],
	associations: [ 'lotus' ],
},
{
	str: 'Shitou',
	gender: 'M',
	tags: [ '#beggar' ],
	associations: [ 'rock', 'stone' ],
},
{
	str: 'Tou',
	gender: 'M',
	tags: [ '#beggar' ],
	associations: [ 'head' ],
},
{
	str: 'Houzi',
	gender: 'N',
	tags: [ '#beggar' ],
	associations: [ 'monkey' ],
},
{
	str: 'Hou',
	gender: 'N',
	tags: [ '#beggar' ],
	associations: [ 'monkey' ],
},
{
	str: 'Dan',
	gender: 'N',
	tags: [ '#beggar' ],
	associations: [ 'egg' ],
},
{
	str: 'Niu',
	gender: 'F',
	tags: [ '#beggar' ],
	associations: [ 'girl' ],
},
{
	str: 'Gu',
	gender: 'F',
	tags: [ '#beggar' ],
	associations: [ 'aunt' ],
},
{
	str: 'Tang',
	gender: 'M',
	tags: [ '#constable' ],
	associations: [ 'court', 'hall', 'yamen hall' ],
},
{
	str: 'Xiang',
	gender: 'N',
	tags: [ '#constable', '#loyalist', '#merchant', '#playboy/young_master' ],
	associations: [ 'aromatic', 'auspicious', 'fragrant', 'glide', 'in the direction of', 'lucky', 'propitious', 'soar', 'sweet-smelling', 'toward' ],
},
{
	str: 'Jun',
	gender: 'N',
	tags: [ '#constable', '#government_official', '#merchant', '#scholar', '#soldier' ],
	associations: [ 'elegant', 'handsome', 'lord', 'monarch', 'princess', 'smart', 'spirited horse', 'talented' ],
},
{
	str: 'Liu',
	gender: 'N',
	tags: [ '#constable', '#playboy/young_master', '#thief' ],
	associations: [ 'keep', 'remain', 'retain', 'six', 'sixth', 'stay', 'to leave', 'willow' ],
},
{
	str: 'Hong',
	gender: 'N',
	tags: [ '#constable', '#constable', '#entertainer', '#farmer', '#scholar' ],
	associations: [ 'big', 'flood', 'goose', 'grand', 'great', 'magnificent', 'popular', 'red', 'revolutionary', 'vast' ],
},
{
	str: 'Wang',
	gender: 'N',
	tags: [ '#constable', '#fisher', '#government_official' ],
	associations: [ 'expect', 'flourishing', 'gaze', 'hope', 'king', 'prosperous', 'royal', 'view', 'watch' ],
},
{
	str: 'Ping',
	gender: 'N',
	tags: [ '#constable' ],
	associations: [ 'calm', 'peace' ],
},
{
	str: 'Jin',
	gender: 'N',
	tags: [ '#constable', '#merchant', '#merchant', '#shop_owner' ],
	associations: [ 'brilliance', 'gold', 'metal' ],
},
{
	str: 'Fang',
	gender: 'F',
	tags: [ '#constable' ],
	associations: [ 'direction', 'square', 'way' ],
},
{
	str: 'Sanfeng',
	gender: 'M',
	tags: [ '#dedicated_martial_practitioner' ],
	associations: [ 'legendary real-life daoist who is credited with inventing taichi', 'the given name of zhan sanfeng' ],
},
{
	str: 'Zongyuan',
	gender: 'M',
	tags: [ '#dedicated_martial_practitioner' ],
	associations: [ 'a tang dynasty poet', 'the given name of liu zongyuan' ],
},
{
	str: 'Zong',
	gender: 'M',
	tags: [ '#dedicated_martial_practitioner' ],
	associations: [ 'ancestor', 'model', 'purpose', 'school', 'sect' ],
},
{
	str: 'Yewen',
	gender: 'M',
	tags: [ '#dedicated_martial_practitioner' ],
	associations: [ 'cantonese martial artist and teacher of bruce lee', 'the surname and given name of ip man' ],
},
{
	str: 'Xie',
	gender: 'N',
	tags: [ '#dedicated_martial_practitioner', '#thief' ],
	associations: [ 'apologize', 'decline', 'thank' ],
},
{
	str: 'Chan',
	gender: 'N',
	tags: [ '#dedicated_martial_practitioner' ],
	associations: [ 'zen' ],
},
{
	str: 'Daniang',
	gender: 'F',
	tags: [ '#dedicated_martial_practitioner' ],
	associations: [ 'aunt' ],
},
{
	str: 'Jiu',
	gender: 'F',
	tags: [ '#dedicated_martial_practitioner' ],
	associations: [ 'nine' ],
},
{
	str: 'Ren',
	gender: 'M',
	tags: [ '#detective' ],
	associations: [ 'benevolence', 'humane' ],
},
{
	str: 'Bin',
	gender: 'M',
	tags: [ '#detective' ],
	associations: [ 'ornamental', 'refined' ],
},
{
	str: 'Rui',
	gender: 'M',
	tags: [ '#detective' ],
	associations: [ 'astute', 'intelligent', 'perspicacious' ],
},
{
	str: 'Zhi',
	gender: 'N',
	tags: [ '#detective', '#doctor', '#doctor' ],
	associations: [ 'annals', 'chinese angelica (medicinal plant)', 'inform', 'know', 'notify', 'record', 'will' ],
},
{
	str: 'Liang',
	gender: 'N',
	tags: [ '#detective', '#soldier' ],
	associations: [ 'beautiful', 'bright', 'docile', 'good', 'light' ],
},
{
	str: 'Ru',
	gender: 'F',
	tags: [ '#detective' ],
	associations: [ 'as if', 'like' ],
},
{
	str: 'Xun',
	gender: 'N',
	tags: [ '#detective', '#playboy/young_master' ],
	associations: [ 'nettle', 'search', 'seek' ],
},
{
	str: 'Huatuo',
	gender: 'M',
	tags: [ '#doctor' ],
	associations: [ 'hua tuo was a famous doctor during the han dynasty' ],
},
{
	str: 'Tuo',
	gender: 'M',
	tags: [ '#doctor' ],
	associations: [ 'to carry on the back' ],
},
{
	str: 'Miao',
	gender: 'N',
	tags: [ '#doctor' ],
	associations: [ 'profound', 'remote' ],
},
{
	str: 'Cheng',
	gender: 'N',
	tags: [ '#doctor', '#loyalist' ],
	associations: [ 'accomplish', 'complete', 'finish', 'journey', 'order', 'rule', 'succeed' ],
},
{
	str: 'Zhong',
	gender: 'N',
	tags: [ '#doctor', '#scholar' ],
	associations: [ 'bell', 'chime', 'intermediate', 'middle', 'second month of a season', 'timepice' ],
},
{
	str: 'Hu',
	gender: 'N',
	tags: [ '#doctor', '#farmer' ],
	associations: [ 'beard', 'foreign', 'outrageous', 'reckless', 'tiger' ],
},
{
	str: 'Run',
	gender: 'M',
	tags: [ '#entertainer' ],
	associations: [ 'embellish', 'moist', 'profit', 'smooth' ],
},
{
	str: 'Ji',
	gender: 'M',
	tags: [ '#entertainer' ],
	associations: [ 'name of a mountain' ],
},
{
	str: 'Kang',
	gender: 'M',
	tags: [ '#entertainer', '#government_official' ],
	associations: [ 'abundant', 'healthy', 'peaceful' ],
},
{
	str: 'Chao',
	gender: 'N',
	tags: [ '#entertainer' ],
	associations: [ 'court', 'dynasty', 'government' ],
},
{
	str: 'Chuan',
	gender: 'N',
	tags: [ '#entertainer' ],
	associations: [ 'plain', 'river', 'sichuan province' ],
},
{
	str: 'Xian',
	gender: 'F',
	tags: [ '#entertainer' ],
	associations: [ 'immortal' ],
},
{
	str: 'Fengxian',
	gender: 'F',
	tags: [ '#entertainer' ],
	associations: [ 'garden balsam' ],
},
{
	str: 'Daye',
	gender: 'M',
	tags: [ '#farmer' ],
	associations: [ 'great cause', 'great undertaking' ],
},
{
	str: 'Tie',
	gender: 'M',
	tags: [ '#farmer' ],
	associations: [ 'indisputable', 'iron' ],
},
{
	str: 'Gua',
	gender: 'N',
	tags: [ '#farmer' ],
	associations: [ 'melon' ],
},
{
	str: 'Wa',
	gender: 'N',
	tags: [ '#farmer' ],
	associations: [ 'baby', 'child', 'doll' ],
},
{
	str: 'You',
	gender: 'N',
	tags: [ '#farmer' ],
	associations: [ 'be', 'exist', 'have' ],
},
{
	str: 'Chun',
	gender: 'N',
	tags: [ '#farmer', '#government_official' ],
	associations: [ 'genuine', 'honest', 'pure', 'spring', 'youth' ],
},
{
	str: 'Cui',
	gender: 'F',
	tags: [ '#farmer' ],
	associations: [ 'blue-green', 'emerald', 'green' ],
},
{
	str: 'Fa',
	gender: 'M',
	tags: [ '#fisher' ],
	associations: [ 'send out', 'show', 'to develop', 'to issue' ],
},
{
	str: 'Jiang',
	gender: 'M',
	tags: [ '#fisher' ],
	associations: [ 'river' ],
},
{
	str: 'Zai',
	gender: 'M',
	tags: [ '#fisher', '#soldier' ],
	associations: [ 'carry', 'child', 'convey', 'hold', 'lift', 'young man' ],
},
{
	str: 'A',
	gender: 'N',
	tags: [ '#fisher', '#shop_owner' ],
	associations: [ 'no meaning', 'sound word' ],
},
{
	str: 'Zhou',
	gender: 'N',
	tags: [ '#fisher' ],
	associations: [ 'boat' ],
},
{
	str: 'Xu',
	gender: 'N',
	tags: [ '#fisher' ],
	associations: [ 'allow', 'permit', 'promise' ],
},
{
	str: 'He',
	gender: 'N',
	tags: [ '#fisher', '#merchant' ],
	associations: [ 'lotus', 'river' ],
},
{
	str: 'Haiyan',
	gender: 'F',
	tags: [ '#fisher' ],
	associations: [ 'storm petrel (bird)' ],
},
{
	str: 'Lu',
	gender: 'F',
	tags: [ '#fisher' ],
	associations: [ 'green' ],
},
{
	str: 'Caixia',
	gender: 'F',
	tags: [ '#fisher', '#servant' ],
	associations: [ 'rosy or pink clouds' ],
},
{
	str: 'Cai',
	gender: 'N',
	tags: [ '#fisher', '#servant', '#shop_owner' ],
	associations: [ 'appluase', 'cheer', 'color', 'colored', 'money', 'prize', 'variety', 'wealth' ],
},
{
	str: 'Xuan',
	gender: 'N',
	tags: [ '#government_official' ],
	associations: [ 'announce', 'declare publicly' ],
},
{
	str: 'Bi',
	gender: 'N',
	tags: [ '#government_official', '#servant' ],
	associations: [ 'blue', 'bluish green', 'green jade', 'jade' ],
},
{
	str: 'Nie',
	gender: 'F',
	tags: [ '#government_official' ],
	associations: [ 'whisper' ],
},
{
	str: 'Su wu',
	gender: 'M',
	tags: [ '#loyalist' ],
	associations: [ 'a famous chinese statesman from the han dynasty' ],
},
{
	str: 'Su',
	gender: 'M',
	tags: [ '#loyalist' ],
	associations: [ 'awake', 'recover consciousness', 'wake' ],
},
{
	str: 'Tianxiang',
	gender: 'M',
	tags: [ '#loyalist' ],
	associations: [ 'blessed by heaven' ],
},
{
	str: 'Qin',
	gender: 'N',
	tags: [ '#loyalist', '#loyalist', '#shop_owner' ],
	associations: [ 'diligent', 'dynasty name', 'industrious', 'qin dynasty', 'thoughtful' ],
},
{
	str: 'Heng',
	gender: 'N',
	tags: [ '#loyalist' ],
	associations: [ 'constant', 'fixed', 'permanent' ],
},
{
	str: 'Qingfeng',
	gender: 'N',
	tags: [ '#loyalist' ],
	associations: [ 'cool breeze', 'pure and honest' ],
},
{
	str: 'Qiong',
	gender: 'F',
	tags: [ '#loyalist' ],
	associations: [ 'beautiful', 'fine jade', 'jaster' ],
},
{
	str: 'Tong',
	gender: 'N',
	tags: [ '#loyalist', '#playboy/young_master' ],
	associations: [ 'crimson', 'red', 'scarlet', 'vermilion' ],
},
{
	str: 'Wanguan',
	gender: 'M',
	tags: [ '#merchant' ],
	associations: [ 'millionaire', 'ten thousand strings of cash', 'wealthy' ],
},
{
	str: 'Liuxiang',
	gender: 'M',
	tags: [ '#playboy/young_master' ],
	associations: [ 'chu liuxiang', 'the given name of a famous character from wuxia novels' ],
},
{
	str: 'Huai',
	gender: 'M',
	tags: [ '#playboy/young_master' ],
	associations: [ 'bosom', 'heart', 'mind' ],
},
{
	str: 'Xunhuan',
	gender: 'M',
	tags: [ '#playboy/young_master' ],
	associations: [ 'frolic', 'seek pleasure' ],
},
{
	str: 'Mantian',
	gender: 'N',
	tags: [ '#playboy/young_master' ],
	associations: [ 'boundless', 'everywhere', 'filling the whole sky', 'limitless' ],
},
{
	str: 'Man',
	gender: 'N',
	tags: [ '#playboy/young_master' ],
	associations: [ 'be everywhere', 'inundate', 'overflow' ],
},
{
	str: 'Xin’nian',
	gender: 'F',
	tags: [ '#playboy/young_master' ],
	associations: [ 'aspiration', 'idea', 'thought' ],
},
{
	str: 'Nian',
	gender: 'N',
	tags: [ '#playboy/young_master', '#shop_owner' ],
	associations: [ 'idea', 'thought' ],
},
{
	str: 'Sa',
	gender: 'M',
	tags: [ '#scholar' ],
	associations: [ 'sound of the wind' ],
},
{
	str: 'Ban',
	gender: 'N',
	tags: [ '#scholar' ],
	associations: [ 'class', 'squad', 'team' ],
},
{
	str: 'Zhao',
	gender: 'N',
	tags: [ '#scholar', '#scholar' ],
	associations: [ 'bright', 'clear', 'manifest' ],
},
{
	str: 'Ruan',
	gender: 'F',
	tags: [ '#scholar' ],
	associations: [ 'ancient musical instrument' ],
},
{
	str: 'Bao',
	gender: 'M',
	tags: [ '#servant' ],
	associations: [ 'gem', 'treasure' ],
},
{
	str: 'Laifu',
	gender: 'N',
	tags: [ '#servant' ],
	associations: [ 'bring', 'come' ],
},
{
	str: 'Rou',
	gender: 'F',
	tags: [ '#servant' ],
	associations: [ 'flexible', 'soft', 'supple' ],
},
{
	str: 'Gui',
	gender: 'N',
	tags: [ '#shop_owner', '#shop_owner' ],
	associations: [ 'expensive', 'noble', 'precious' ],
},
{
	str: 'Aicai',
	gender: 'M',
	tags: [ '#shop_owner' ],
	associations: [ 'to love money' ],
},
{
	str: 'Fen',
	gender: 'N',
	tags: [ '#shop_owner' ],
	associations: [ 'rouse', 'to exert oneself' ],
},
{
	str: 'An',
	gender: 'N',
	tags: [ '#shop_owner', '#soldier' ],
	associations: [ 'calm', 'content', 'quiet', 'safe' ],
},
{
	str: 'Anbang',
	gender: 'M',
	tags: [ '#soldier' ],
	associations: [ 'to bring order to a country', 'to bring peace to a country', 'to bring stability to a country' ],
},
{
	str: 'Bang',
	gender: 'M',
	tags: [ '#soldier' ],
	associations: [ 'country', 'nation', 'state' ],
},
{
	str: 'Bu',
	gender: 'N',
	tags: [ '#soldier' ],
	associations: [ 'cloth', 'fabric', 'publish', 'spread' ],
},
{
	str: 'Mulan',
	gender: 'F',
	tags: [ '#soldier' ],
	associations: [ 'the given name of hua mulan = the most famous female soldier in the history of china' ],
},
{
	str: 'Lan',
	gender: 'F',
	tags: [ '#soldier' ],
	associations: [ 'orchid' ],
},
{
	str: 'Shou',
	gender: 'M',
	tags: [ '#thief' ],
	associations: [ 'arm', 'hand' ],
},
{
	str: 'Che',
	gender: 'M',
	tags: [ '#thief' ],
	associations: [ 'car', 'carriage', 'vehicle' ],
},
]

export {
	FIRST_NAME_ENTRIES,
}
